### ISSUE TITLE
It seems that all the image urls  unable to link the server。Is it my network problem？

### ISSUE THREAD

**Issue by macy11** [skydoves/Pokedex-AR#4]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by macy11** [comment]
2021-08-18 15:15:06.096 4570-4570/com.skydoves.pokedexar W/Glide: Load failed for https://pokeres.bastionbot.org/images/pokemon/39.png with size [420x420]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: -1
2021-08-18 15:15:06.096 4570-4570/com.skydoves.pokedexar I/Glide: Root cause (1 of 1)

**Comment by skydoves** [comment]
As you can see from the about the exception, the root URL link is incorrect. 
Please use the correct URL and this issue seems not related to this repository. :)
